### ISSUE TITLE
OSError: Invalid data format: can't load _dawg.Dictionary

### ISSUE THREAD

**Issue by mobileunit** [DuyguA/DEMorphy#1]
Hi Duygu, 

thanks for the tool DEMorphy. I was trying to install the tool using your Readme 

$ git clone https://github.com/DuyguA/DEMorphy
$ cd DEMorphy
$ python setup.py install

All seems to work out properly. When starting your code example in Python I get the error message 

OSError: Invalid data format: can't load _dawg.Dictionary

Do I somehow have to connetc the installation to the dictionary sources available here? 

https://github.com/DuyguA/german-morph-dictionaries

I tried to put them simply in the demorphy/morph_dict/ folder but that doesn't seem to work. 

Do you have a clue why it is not working for me?

Many thanks and best regards, Andy

**Comment by DuyguA** [comment]
Hello,

Yes, it seems that I uploaded the old version of README file. Due to Github restrictions, I changed downloading dictionary a bit. You need to download demorphy/data/words.dg manually  from this repo and then launch the installation script. 

I'll change the README soon. Thanx for detecting.

**Comment by mobileunit** [comment]
Wooohooo :D 
It is working now! Thanks a lot!!!
Best, Andy

**Comment by DuyguA** [comment]
Thanks a lot for noticing also, I uploaded the wrong version😯

**Comment by AlessandroVol23** [comment]
Hi, I've got the same error with this example script:
```python
from demorphy import Analyzer
print("after import")
lemmatizer = Analyzer()
# Same with lemmatizer = Analyzer(char_subs_allowed=True)
print("test")
```

I've installed the package within a virtual env in python 3.6.8 with the command `python setup.py install`

**Comment by DuyguA** [comment]
Hello @AlessandroVol23  , 

Did you follow the this instruction in the README:

> Download the dictionary file demorphy/data/words.dg and replace it under the corresponding directory again. Then you're ready to launch the setup script:

Before launching the install script, one needs to download the words graph manually.

**Comment by AlessandroVol23** [comment]
Hi, yes that was my mistake at the beginning, I downloaded the file via `git lfs pull` and now I can initialize the Analyzer. Thanks

**Comment by DuyguA** [comment]
I'll close the issue then , would that be OK?
