### ISSUE TITLE
Error downloading words.dg

### ISSUE THREAD

**Issue by AleksTk** [DuyguA/DEMorphy#3]
Failed to download words.df with git lfs. Can you share it elsewhere?

>git checkout -f HEAD

Downloading demorphy/data/words.dg (171 MB)
Error downloading object: demorphy/data/words.dg (e2a8b8c): Smudge error: Error downloading demorphy/data/words.dg (e2a8b8c41db51219597e48b6a7bb952c32cd8426e92440248c12f73e399aeb6b): batch response: This repository is over its data quota.
Purchase more data packs to restore access.

**Comment by DuyguA** [comment]
Hi Alex,

I think I exceeded GitLFS  bandwidth quota due to many downloads. Yes of course, I can store it elsewhere. I'll fix the bandwidth issue quickly, so you can download right now. Would that be OK?

**Comment by AleksTk** [comment]
>I'll fix the bandwidth issue quickly, so you can download right now. Would that be OK?

That would be great! Thanks for quick response.

**Comment by DuyguA** [comment]
You can try downloading again now  :wink:

**Comment by AleksTk** [comment]
Got the data! Thank you!
